$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: Pipeline for Amazon Fine Goods Reviews
display_name: amazon-reviews-pipeline

# <inputs_and_outputs>
outputs: 
  pipeline_job_trained_model:
    type: mlflow_model
    mode: rw_mount
  pipeline_job_predictions:
    mode: rw_mount 
  pipeline_job_score_report:
    mode: rw_mount
# </inputs_and_outputs>

# <jobs>
settings:
  default_datastore: azureml:amazondatastore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

jobs:
  prep_job:
    type: command
    component: ./prep/prep.yml
    inputs:
      raw_data: 
        type: uri_file
        path: azureml://subscriptions/ce96fbca-fc23-466f-87e4-9b8cb5316116/resourcegroups/rg-review-analysis-teamc/workspaces/aml-review-analysis-teamc1/datastores/workspaceblobstore/paths/LocalUpload/041545eb1f3923dc31eca1b024cb3ba3/reviews.csv
      prep_data: reviews-prepped.csv
    outputs:
      prep_data: 
    

  train_job:
    type: command
    component: ./train/train.yml
    inputs:
      training_data: ${{parent.jobs.prep_job.outputs.prep_data}}
    outputs:
      model_output: ${{parent.outputs.pipeline_job_trained_model}}
  
# </jobs>


