$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: Tuning hyperparameters for Amazon Fine Goods Reviews
display_name: amazon-reviews-pipeline
experiment_name: reviews_analysis__train
tags:
  model: lda
  task : clustering

inputs:
  training_data: 
    type: uri_file
    path: azureml:reviews-preprocessed:3

# <inputs_and_outputs>
outputs: 
  pipeline_job_trained_model:
    type: mlflow_model
    mode: rw_mount
  pipeline_job_predictions:
    mode: rw_mount 
  pipeline_job_score_report:
    mode: rw_mount
# </inputs_and_outputs>

# <jobs>
settings:
  default_datastore: azureml:amazondatastore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

jobs:
  sweep_step:
    type: sweep
    inputs:
      training_data: ${{parent.inputs.training_data}}
      registered_model_name: lda-model
    outputs:
      model_output: ${{parent.outputs.pipeline_job_trained_model}}
    sampling_algorithm: random
    search_space:
      nb_passes:
        type: choice
        values: [10, 20, 30]
    trial: ../train/train.yml
    objective:
      goal: maximize
      primary_metric: coherence_score
    limits:
      max_total_trials: 10
      max_concurrent_trials: 3
      timeout: 36000 # 10 hours
      trial_timeout: 720 # 20 mins
  
# </jobs>


