$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: Tuning hyperparameters for Amazon Fine Goods Reviews
display_name: amazon-reviews-pipeline
experiment_name: reviews_analysis__train
tags:
  model: kmeans
  task : clustering

inputs:
  training_data: 
    type: uri_file
    path: azureml:reviews-preprocessed:3

# <inputs_and_outputs>
outputs: 
  pipeline_job_trained_model:
    type: mlflow_model
    mode: rw_mount
  pipeline_job_predictions:
    mode: rw_mount 
  pipeline_job_score_report:
    mode: rw_mount
# </inputs_and_outputs>

# <jobs>
settings:
  default_datastore: azureml:amazondatastore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

jobs:
  sweep_step:
    type: sweep
    inputs:
      training_data: ${{parent.inputs.training_data}}
      registered_model_name: kmeans-model
    outputs:
      model_output: ${{parent.outputs.pipeline_job_trained_model}}
      test_data:
    sampling_algorithm: random
    search_space:
      init_size:
        type: choice
        values: [1000, 2000, 3000]
      batch_size:
        type: choice
        values: [1000, 2000, 3000]
      n_init:
        type: choice
        values: [1, 2, 3, 4, 5]
    trial: ./train/train.yml
    objective:
      goal: maximize
      primary_metric: model_inertia
    limits:
      max_total_trials: 5
      max_concurrent_trials: 3
      timeout: 7200 # 2 hours
      trial_timeout: 720 # 20 mins
  
# </jobs>


