$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: Tuning hyperparameters for Amazon Fine Goods Reviews
display_name: amazon-reviews-pipeline
experiment_name: reviews_analysis__train
tags:
  model: svm-doc2vec
  task : classification

inputs:
  training_data: 
    type: uri_file
    path: azureml:reviews-preprocessed:3

# <inputs_and_outputs>
outputs: 
  pipeline_job_trained_model:
    type: mlflow_model
    mode: rw_mount
  pipeline_job_predictions:
    mode: rw_mount 
  pipeline_job_score_report:
    mode: rw_mount
# </inputs_and_outputs>

# <jobs>
settings:
  default_datastore: azureml:amazondatastore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

jobs:
  sweep_step:
    type: sweep
    inputs:
      training_data: ${{parent.inputs.training_data}}
      registered_model_name: svm-model-doc2vec
      vectorizer : doc2vec
      window: 3
      workers: 2
    outputs:
      model_output: ${{parent.outputs.pipeline_job_trained_model}}
      test_data:
    sampling_algorithm: random
    search_space:
      vector_size:
        type: choice
        values: [2000, 8000, 16000]
      min_count:
        type: choice
        values: [4, 8, 16]
      epochs:
        type: choice
        values: [5, 10, 15]
    trial: ./train/train.yml
    objective:
      goal: maximize
      primary_metric: training_accuracy_score
    limits:
      max_total_trials: 20
      max_concurrent_trials: 2
      timeout: 36000 # 3 hour
      trial_timeout: 720 # 20 mins
  
# </jobs>

