# <component>
$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_naive_bayes_model
display_name: TrainNaiveBayesModel
version: 1
type: command
inputs:
  training_data: 
    type: uri_file
  registered_model_name:
    type: string
outputs:
  model_output:
    type: mlflow_model
code: ./
environment: azureml:keras-env@latest
command: >-
  python train.py 
      --training_data ${{inputs.training_data}} 
      --registered_model_name ${{inputs.registered_model_name}} 
# </component>