# <component>
$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_linear_regression_model
display_name: TrainLinearRegressionModel
version: 1
type: command
inputs:
  training_data: 
    type: uri_file
outputs:
  model_output:
    type: mlflow_model
  test_data:
    type: uri_folder
code: ./
environment: azureml://keras-env:v6
command: >-
  python train.py 
      --prep_data ${{inputs.prep_data}} 
      --registered_model_name ${{inputs.registered_model_name}} 
# </component>