# <component>
$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_gradient_boosting_model
display_name: TrainGradientBoostingModel
tags: 
  model : gradient-boost
  task : classification
version: 1
type: command
inputs:
  training_data: 
    type: uri_file
  registered_model_name: 
    type: string
    default: xgboost-model
outputs:
  model_output:
    type: mlflow_model
  test_data:
    type: uri_folder
code: ./
environment: azureml:keras-env:v10
command: >-
  python train.py 
  --training_data ${{inputs.training_data}} 
  --model_output ${{outputs.model_output}}
  --registered_model_name ${{inputs.registered_model_name}} 
# </component>