name: sweep-reviews-training-pipeline
on:
  push:
    branches:
      - dev
    paths:
      - .github/workflows/sweep-pipeline-job.yml
      - code/aml/naive-bayes/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with: 
        python-version: '3.11'
    - name: Run Python tests
      run: pip install -U pytest pandas numpy nltk && pytest
      working-directory: code/aml/naive-bayes/src
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Setup AML Workspace
      run: bash setup.sh
      working-directory: code/aml/naive-bayes/src/pipelines
      continue-on-error: true
    - name: Run AML pipeline
      run: bash -x run-job.sh reviews-pipeline-sweep.yml
      working-directory: code/aml/naive-bayes/src/pipelines
